# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1385039ce16008bb0501ee1d225254c06ae9ae85d9f6187359978b556199b111a126530612c4af6bbb0020464cec7d79944c847f2b429358a32c06e9aaac3f

test:
  secret_key_base: f97b530da62cde7e4121d13d5b197623704671e93377c222424780e938cfa27bf23b5dd793e728341a1d319c78baabefede2a0ec1f1176575536a1484a1f44a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
